steps:
  - label: ':hammer: Tests'
    command: 'echo "hello world!" && export PACT_RAN=true && export TEST_STATUS=failed'
    plugins:
      - ./.buildkite/plugins/datadog-metrics-buildkite-plugin2:
          metric: pact.contract.verified.$TEST_STATUS
          api_key: 342423423423
          tags:
            - "pacticipant:ProductService"
            - "domain:servicing"
            - "branch:master"
            - "version:b43bEVWQv"
          type: count
          value: 1
          condition: $PACT_RAN