#!/bin/bash


if ! ${BUILDKITE_PLUGIN_DATADOG_METRICS_CONDITION}; then
  echo "datadog metric is skipped"
  exit 0
fi

if [[ -n "${BUILDKITE_PLUGIN_DATADOG_METRICS_API_KEY}" ]]; then
  DATADOG_API_KEY="${BUILDKITE_PLUGIN_DATADOG_METRICS_API_KEY}"
else
  DATADOG_API_KEY_PATH="/latitude/cnp/datadog/api-key"
  if [[ -n "${BUILDKITE_PLUGIN_DATADOG_METRICS_API_KEY_PATH}" ]]; then
    DATADOG_API_KEY_PATH="${BUILDKITE_PLUGIN_DATADOG_METRICS_API_KEY_PATH}"
  fi
  DATADOG_API_KEY=$(aws ssm get-parameter --name "${DATADOG_API_KEY_PATH}" --with-decryption --query Parameter.Value --with-decryption --output text)
fi
if [[ -z "${DATADOG_API_KEY}" ]]; then
  buildkite-agent annotate --style "warning" --context "datadog-metrics-plugin" "Skippping Datadog metrics plugin due to missing api key in SSM. Please set the Datadog API key in SSM (of the account the Buildkite agent is running on) with the parameter name as '${DATADOG_API_KEY_PATH}'. You can find your API keys at https://app.datadoghq.com/account/settings#api ."
  exit 0
fi

DEFAULT_DD_TAGS_CSV=$(buildkite-agent meta-data get "default_tags")
set -eu -o pipefail

# Combine the tags into an escaped tags csv
IFS=',' read -r -a DD_TAGS_ARRAY <<< "$DEFAULT_DD_TAGS_CSV"
for TAG in $(compgen -A variable | grep -E "^BUILDKITE_PLUGIN_DATADOG_METRICS_TAGS_"); do
  DD_TAGS_ARRAY+=("${!TAG}")
done
DD_TAGS_ARRAY+=("source:buildkite")
ESCAPED_TAGS_ARRAY_CSV=""
for i in "${DD_TAGS_ARRAY[@]}"; do
  ESCAPED_TAGS_ARRAY_CSV="$ESCAPED_TAGS_ARRAY_CSV,\"$(eval echo "${i}")\""
done
ESCAPED_TAGS_ARRAY_CSV="${ESCAPED_TAGS_ARRAY_CSV:1}"


CURRENTTIME=$(date +%s)
curl  -X POST -H "Content-type: application/json" \
-d "{ \"series\" :
         [{\"metric\":${BUILDKITE_PLUGIN_DATADOG_METRICS_METRIC},
          \"points\":[[${CURRENTTIME}, ${BUILDKITE_PLUGIN_DATADOG_METRICS_VALUE}]],
          \"type\":${BUILDKITE_PLUGIN_DATADOG_METRICS_TYPE},
          \"tags\":[${ESCAPED_TAGS_ARRAY_CSV}]}
        ]
}" \
"https://api.datadoghq.com/api/v1/series?api_key=${DATADOG_API_KEY}"
